apiVersion: v1
kind: PersistentVolume 
metadata:
  name: pv-local-1
spec: 
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessMode:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path:/mnt/data
